// TypeScript definitions for CubeCobra global card frequency data.
// Generated by download-cubecobra-exports.ts and loaded at runtime.

export interface CubeCobraFrequencyData {
    generatedAt: string;
    recencyMonths: number;
    cubesLastModified?: string | null;
    cubeCount: Record<string, number>;
    broadGroups: Record<string, string[]>;
    cards: Record<string, Record<string, number>>;
}
