export interface PresetCollection {
    name: string;
    label: string;
}

/**
 * Visible preset collections in the UI.
 * Each `name` maps to a preloads/cubes-{name}.json file generated by preload-cube-data.ts.
 * If the file doesn't exist at build time it is silently omitted from the dropdown.
 */
export const presetCollections: PresetCollection[] = [
    { name: 'wotc', label: 'WotC MTGO/Arena' },
    { name: 'cubecobra-top100', label: 'CubeCobra Top 100' },
    { name: 'peasant', label: 'Peasant Cubes' },
    { name: 'shoebox-2026', label: 'Shoebox 2026' },
    { name: 'cube-corner-2026', label: 'Cube Corner @ Amsterdam 2026' },
];
